port: 80
TLSPort: 443
allowDirectoryIndex: true
sitesAvailable:
  - path: "/var/www/html"
    index: "index.html"
    host: "{all:.*}"
    redirectNonTLS: false
    compress: true
    compressionLevel: 9

disableHealthCheck: false
