name: SPA Server


on:
  push:
    branches:
      - "*"


env:
  CI: true
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REG: ghcr.io


jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Code analysis
        run: ./run_static_analysis.sh


  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Unit tests
        run: ./run_unit_tests.sh


  build:
    name: Build
    needs: [check, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build image
        run: ./scripts/build.sh
