name: SPA Server


on:
  push:
    branches:
      - "*"

env:
  CI: true
  DOCKER_IMAGE_NAME: ghcr.io/defencedigital/spa-server

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare labels and tags
        id: prep
        run: |
          SEMVER-$(./semver.sh)
          BRANCH=$(echo ${GITHUB_REF##*/} | tr '[A-Z]' '[a-z]')
          SANITISED_REPOSITORY_NAME=$(echo ${{ github.event.repository.name }} | sed -e 's|\.|-|g')
          TAGS="${{ env.DOCKER_IMAGE_NAME }}:$(echo ${GITHUB_SHA::8}),${{ env.DOCKER_IMAGE_NAME }}:$(echo ${BRANCH} | sed -e 's|\.|-|g')"
          if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
            TAGS="$TAGS,${{ env.DOCKER_IMAGE_NAME }}:latest,${{ env.DOCKER_IMAGE_NAME }}:$SEMVER"
          fi
          echo ::set-output name=tags::${TAGS}
          LABELS="org.opencontainers.image.revision=$(echo ${GITHUB_SHA::8})"
          LABELS="$LABELS,org.opencontainers.image.created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          LABELS="$LABELS,org.opencontainers.image.version=$SEMVER"
          LABELS="$LABELS,com.github.repo.branch=$BRANCH"
          LABELS="$LABELS,com.github.repo.dockerfile=Dockerfile"
          echo ::set-output name=labels::${LABELS}
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # Uncomment following to enable push only on merge to the master
          # push: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: ${{ steps.prep.outputs.labels }}
          no-cache: false
